using System.Text.Json;

namespace FluidRuntime.Runtime;

public sealed record SustainedCopyRunReport(
    bool Optimized,
    int ProcessId,
    string RenderDriver,
    string AdapterDescription,
    uint AdapterVendorId,
    uint AdapterDeviceId,
    string AdapterLuid,
    long EventCount,
    long LostSequenceCount,
    long NativeOverrunCount,
    long ObservedCopyCount,
    ulong ObservedCopyBytes,
    long RedundantCopyCount,
    ulong RedundantCopyBytes,
    long ForwardedCopyCount,
    ulong ForwardedCopyBytes,
    long SkippedCopyCount,
    ulong SkippedCopyBytes,
    long PublishedPolicyEpoch,
    long AcknowledgedPolicyEpoch,
    long AppliedPolicyActions,
    string PolicyStatus,
    bool ContentEquivalent,
    bool RollbackRestored,
    string SustainedSourceHash,
    string SustainedDestinationHash,
    double CpuWorkloadMicroseconds,
    double? GpuWorkloadMicroseconds,
    JsonElement TargetReport);

public sealed record SustainedCopyTrialReport(
    int PairIndex,
    string Phase,
    bool IncludedInStatistics,
    string ExecutionOrder,
    bool ContentEquivalent,
    bool RollbackRestoredInBothRuns,
    bool AdapterIdentityMatched,
    double BaselineCpuMicroseconds,
    double OptimizedCpuMicroseconds,
    double? BaselineGpuMicroseconds,
    double? OptimizedGpuMicroseconds,
    SustainedCopyRunReport Baseline,
    SustainedCopyRunReport Optimized);

public sealed record SustainedCopyLabReport(
    string Mode,
    bool TargetOwned,
    bool CooperativeLoad,
    bool RemoteInjection,
    int SustainedBufferBytes,
    int RedundantCopyCountPerOptimizedRun,
    ulong AvoidedCopyBytesPerOptimizedRun,
    int TrialPairsRequested,
    int WarmupPairs,
    int IncludedTrialPairs,
    string OrderingPolicy,
    string AdapterDescription,
    uint AdapterVendorId,
    uint AdapterDeviceId,
    string AdapterLuid,
    bool ContentEquivalent,
    bool RollbackRestoredInAllRuns,
    string ClaimScope,
    bool PerformanceClaimAllowed,
    IReadOnlyList<string> PerformanceClaimBlockers,
    bool CpuRegressionObserved,
    int GpuValidPairCount,
    PairedMetricSummary CpuWorkload,
    PairedMetricSummary? GpuWorkload,
    IReadOnlyList<SustainedCopyTrialReport> Trials);
